# Generated by Django 2.2.6 on 2019-12-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=50000)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(max_length=111)),
                ('email', models.CharField(default='', max_length=111)),
            ],
        ),
    ]
